POST http://127.0.0.1:8000/api/student/save
Content-Type: application/json

{
  "student_name": "rsha",
  "contact_no": "123"
}
###
GET http://127.0.0.1:8000/api/student/get
# GET http://127.0.0.1:8000/student/get